import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/Components/Navbar'
import Footer from '@/Components/Footer'
import { AuthProvider } from './Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Medicare',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Navbar/>

        <AuthProvider>{children}</AuthProvider>

        <Footer/>

        </body>
    </html>
  )
}
